Don't unnecessarily require configuration vars
sensu/sensu-influxdb-handler pull request #24
Opened 2019-02-06 00:19 UTC by flowerysong

InfluxDB connections do not always require a username and password, and we can default to connecting to the default port on localhost (matching the behaviour of the `influx` CLI tool.)

Fixes #23

2019-02-07 17:18 UTC, portertech commented
Cool 👍 What happens when you provide a username OR password (not both)?

2019-02-07 21:22 UTC, flowerysong commented
> Cool +1 What happens when you provide a username OR password (not both)?

Depends on whether authentication is required.

If authentication is disabled on the server, any combination of credentials will be accepted and ignored.

If authentication is enabled, providing a password and no username is rejected: (`error: {"error":"unable to parse authentication credentials"}`), which is the same error returned when authentication is enabled but no credentials are provided. Providing a username and no password will either work (if the user has no password) or be rejected by the server (`error: {"error":"authorization failed"}`)

2019-02-12 23:04 UTC, ccressent approved these changes
Look good to me, thanks @flowerysong!

2019-02-13 20:46 UTC, nikkictl requested changes
I agree with the changes regarding the password and username fields (they should not be required per the Influx docs), which addresses the originating ticket. Thank you for providing justification for the default address and how that behavior is the same for the `influx` cli tool.

Since you have made changes to the help usage, would you mind updating the README with the new help statements? https://github.com/sensu/sensu-influxdb-handler#usage-examples

2019-02-21 17:36 UTC, nikkictl approved these changes
@ccressent thanks for adding that last change in there! And thank you @flowerysong for the submission! Cyril, I'll let you merge away!

2019-02-21 18:34 UTC, merged