Changes to integrate with sensu-plugins-go-library
sensu/sensu-influxdb-handler pull request #28
Opened 2019-05-25 13:44 UTC by sayakju

Update `sensu-influxdb-handler` to use new `sensu-plugins-go-library`

2019-06-03 16:58 UTC, nikkictl requested changes
Loving the cleanup and refactors.. a few comments.

2019-06-03 16:58 UTC, nikkiki commented on main.go
> +			Shorthand: "s",
There is no shorthand for the precision field.
```suggestion
			Shorthand: "",
```

2019-06-03 16:58 UTC, nikkiki commented on main.go
> +			Default:   "",
`s` is the default value for the precision field.
```suggestion
			Default:   "s",
```

2019-06-03 16:58 UTC, nikkiki commented on Gopkg.toml
> -  name = "github.com/sensu/sensu-go"
https://github.com/sensu/sensu-slack-handler/pull/19#discussion_r289935497

2019-06-05 20:15 UTC, sayakju commented on Gopkg.toml
> -  name = "github.com/sensu/sensu-go"
sensu/sensu-pagerduty-handler#14 (comment)

2019-06-15 16:19 UTC, fguimond commented
@nikkiki - The requested changes were implemented by @sayakju. Could you please review them when you have a chance? Thanks!

2019-06-17 12:38 UTC, nikkictl approved these changes

2019-06-17 12:39 UTC, merged